tinyMCE.addI18n('es.advanced',{
style_select:"Estilos",
font_size:"Tamaño fuente",
fontdefault:"Familia fuente",
block:"Formato",
paragraph:"Párrafo",
div:"Div",
address:"Dirección",
pre:"Preformateado",
h1:"Cabecera 1",
h2:"Cabecera 2",
h3:"Cabecera 3",
h4:"Cabecera 4",
h5:"Cabecera 5",
h6:"Cabecera 6",
blockquote:"Cita o bloque",
code:"Código",
samp:"Código ejemplo",
dt:"Definición del término ",
dd:"efinición de la descripción",
span:"Espacio",
bold_desc:"Negrita (Ctrl+B)",
italic_desc:"Italica (Ctrl+I)",
underline_desc:"Subrayar (Ctrl+U)",
striketrough_desc:"Tachado",
justifyleft_desc:"Alinear a izquierda",
justifycenter_desc:"Alinear al centro",
justifyright_desc:"Alinear a derecha",
justifyfull_desc:"Alineación completa",
bullist_desc:"Lista desordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Anular sangría",
indent_desc:"Guión",
undo_desc:"Deshacer (Ctrl+Z)",
redo_desc:"Rehacer (Ctrl+Y)",
link_desc:"Insertar/editar enlace",
unlink_desc:"Desvincular",
image_desc:"Insertar/editar imagen",
cleanup_desc:"Limpiar código desordenado",
code_desc:"Editar código HTML",
sub_desc:"Subíndice",
sup_desc:"Superíndice",
hr_desc:"Insertar regla horizontal",
removeformat_desc:"Eliminar formato",
custom1_desc:"Su descripción personalizada aqui",
forecolor_desc:"Seleccionar color del texto",
backcolor_desc:"Seleccionar color del fondo",
charmap_desc:"Insertar carácter personalizado",
visualaid_desc:"Cambiar lineas guia/elementos invisibles",
anchor_desc:"Insertar/editar ancla",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Pegar",
image_props_desc:"Propiedades de la imagen",
newdocument_desc:"Nuevo documento",
help_desc:"Ayuda",
blockquote_desc:"Cita o bloque",
clipboard_msg:"Copiar/Cortar/Pegar no está disponible en Mozilla y Firefox.\r\n¿Desea más información sobre este tema?",
path:"Ruta",
newdocument:"¿Está seguro que desea borrar todos los contenidos?",
toolbar_focus:"Saltar a los botones de herramientas - Alt+Q, Saltar al editor - Alt-Z, Saltar a la ruta de los elementos - Alt-X",
more_colors:"Más colores",
	
// Accessibility Strings
shortcuts_desc:'Ayuda Accesibilidad',
help_shortcut:'. Pulse ALT F10 para cargar la barra de herramientas. Pulse ALT 0 para obtener ayuda.',
rich_text_area:"Area de Texto Enriquecido",
toolbar:"Barra de herramientas"
});
