tinyMCE.addI18n('es.advanced_dlg',{
about_title:"Acerca de TinyMCE",
about_general:"Acerca de",
about_help:"Ayuda",
about_license:"Licencia",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Versión",
about_loaded:"Plugins cargados",
anchor_title:"Insertar/editar ancla",
anchor_name:"Nombre del ancla",
anchor_invalid:"Por favor, especifique un nombre de ancla válido. El nombre debe empezar con una letra.",
code_title:"Editor código HTML",
code_wordwrap:"Ajuste de línea",
colorpicker_title:"Seleccionar un color",
colorpicker_picker_tab:"Selector",
colorpicker_picker_title:"Selector Color",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta colores",
colorpicker_named_tab:"Nombre",
colorpicker_template_tab:"Plantilla",
colorpicker_named_title:"Nombre colores",
colorpicker_template_title:"Colores Plantilla",
colorpicker_color:"Color:",
colorpicker_name:"Nombre:",
charmap_title:"Seleccionar carácter personalizado",
image_title:"Insertar/editar imagen",
image_src:"URL imagen",
image_alt:"Descripción imagen",
image_list:"Imagen de la lista",
image_border:"Borde",
image_dimensions:"Dimensiones",
image_vspace:"Espacio Vertical",
image_hspace:"Espacio Horizontal",
image_align:"Alineación",
image_align_baseline:"Línea base",
image_align_top:"Superior",
image_align_middle:"Medio",
image_align_bottom:"Inferior",
image_align_texttop:"Texto superior",
image_align_textbottom:"Texto inferior",
image_align_left:"Izquierda",
image_align_right:"Derecha",
link_title:"Insertar/editar enlace",
link_url:"Enlace URL",
link_target:"Destino",
link_target_same:"Abrir el enlace en la misma ventana",
link_target_blank:"Abrir el enlace en ventana nueva",
link_titlefield:"Título",
link_is_email:"La URL que ha introducido parece ser una dirección de correo electrónico, ¿Desea agregar el prefijo requerido mailto:?",
link_is_external:"La URL que ha introducido parece enlace externo, ¿Desea añadir el prefijo http:// necesario?",
link_list:"Lista de enlaces",
accessibility_help:"Ayuda Accesibilidad",
accessibility_usage_title:"Uso General"
});
